### PR TITLE
Remove unecessary $apply

### PR DESCRIPTION
**Pull request by cjh1**
This was causing "Error: $digest already in progress"

### CODE REVIEW

**Comment by cjh1** [comment]
@jourdain @TristanWright @scottwittenburg Can you take a look at this fix.

**Comment by TristanWright** [comment]
Was this error happening every time?

**Comment by jourdain** [comment]
Tristan will get back to you on that with a better fix.

**Comment by scottwittenburg** [comment]
I never noticed that when running the included demo application.

**Comment by TristanWright** [comment]
~~Checking if $digest is going on:~~

Call apply elsewhere.

**Pull request closed without merging**
